spring: 
  profiles:  
    active: 
      - dev
--- 
spring: 
  profiles: dev #开发环境 
  application: springcloud-config-dev 
--- 
spring: 
  profiles: test #开发环境 
  application: springcloud-config-test